import type { PgUUIDBuilder, SetHasRuntimeDefault, SetIsPrimaryKey } from 'drizzle-orm/pg-core';
import { uuid } from 'drizzle-orm/pg-core';
import { v7 } from 'uuid';

/**
 * Builds a UUID primary key with a UUIDv7 default generated by Drizzle on insertion.
 *
 * The default is applied by Drizzle, not PostgreSQL; raw SQL inserts must supply an ID.
 *
 * @param [name] - SQL column name; omit it to use Drizzle's property-name inference.
 * @returns Primary-key column builder with a runtime UUIDv7 default.
 *
 * @example
 * ```ts
 * const records = pgTable('records', { id: generateUuid('id') });
 * ```
 */
export function generateUuid(name?: string): SetHasRuntimeDefault<SetIsPrimaryKey<PgUUIDBuilder>> {
  return uuid(name).primaryKey().$defaultFn(v7);
}
